#!/usr/bin/env bash
# safe — first-run setup: generates .env with the master encryption key and
# auth secret, ready for `docker compose up -d`.
#
# Usage: scripts/setup.sh [--force] [--url <public-url>]
#   --force        overwrite an existing .env (a backup is NOT kept — copy it
#                  yourself first)
#   --url <url>    public URL of the instance (default http://localhost:3000;
#                  prompted for interactively when omitted on a TTY)
set -euo pipefail

# Repo root = parent of this script's directory.
script_dir=$(cd "$(dirname "$0")" && pwd)
root_dir=$(dirname "$script_dir")
env_file="$root_dir/.env"

force=0
url=""
while [ $# -gt 0 ]; do
  case "$1" in
    --force)
      force=1
      ;;
    --url)
      if [ $# -lt 2 ]; then
        echo "error: --url requires a value" >&2
        exit 1
      fi
      url="$2"
      shift
      ;;
    -h | --help)
      sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1 (try --help)" >&2
      exit 1
      ;;
  esac
  shift
done

if [ -e "$env_file" ] && [ "$force" -ne 1 ]; then
  echo "error: $env_file already exists — refusing to overwrite it." >&2
  echo "       It contains your SAFE_MASTER_KEY; losing that key means" >&2
  echo "       losing all stored secrets. Re-run with --force only if you" >&2
  echo "       are sure (back the file up first)." >&2
  exit 1
fi

if ! command -v openssl > /dev/null 2>&1; then
  echo "error: openssl is required to generate keys but was not found." >&2
  exit 1
fi

if [ -z "$url" ]; then
  default_url="http://localhost:3000"
  if [ -t 0 ]; then
    printf "Public URL of this safe instance [%s]: " "$default_url"
    read -r url || url=""
  fi
  url=${url:-$default_url}
fi

case "$url" in
  http://* | https://*) ;;
  *)
    echo "error: --url must be an http(s) URL, got: $url" >&2
    exit 1
    ;;
esac

master_key=$(openssl rand -base64 32)
auth_secret=$(openssl rand -base64 32)

umask 177
cat > "$env_file" <<EOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Used by docker-compose.yml. Keep this file out of version control.

# Master encryption key (KEK). Every project key is wrapped with it.
SAFE_MASTER_KEY="$master_key"

# better-auth signing secret (sessions, cookies).
BETTER_AUTH_SECRET="$auth_secret"

# Public URL users reach this instance at. Must match the address in the
# browser, or sign-in cookies and OAuth callbacks will fail.
SAFE_PUBLIC_URL="$url"
BETTER_AUTH_URL="$url"
EOF
chmod 600 "$env_file"

cat <<EOF

Wrote $env_file (mode 600).

  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!  BACK UP SAFE_MASTER_KEY NOW (password manager / offline).    !!
  !!  It encrypts every secret stored in this instance.            !!
  !!  If you lose it, ALL SECRETS ARE LOST PERMANENTLY.            !!
  !!  No backup of the database can recover them without this key. !!
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Next steps:
  1. docker compose up -d
  2. Open $url and create the first (owner) account.
EOF
